// Generated by CoffeeScript 1.11.1
var Objectlike, PureObject, SortedArray, Typle, assertType, defaultCompare;

SortedArray = require("sorted-array");

PureObject = require("PureObject");

assertType = require("assertType");

Typle = require("Typle");

Objectlike = Typle([Object, PureObject]);

defaultCompare = function(a, b) {
  if (a.key > b.key) {
    return 1;
  } else {
    return -1;
  }
};

module.exports = function(obj, compare) {
  var clone, i, key, len, pairs, ref, ref1, value;
  if (compare == null) {
    compare = defaultCompare;
  }
  assertType(obj, Objectlike);
  pairs = SortedArray([], compare);
  for (key in obj) {
    value = obj[key];
    pairs.insert({
      key: key,
      value: value
    });
  }
  clone = PureObject.test(obj) ? Object.create(null) : {};
  ref = pairs.array;
  for (i = 0, len = ref.length; i < len; i++) {
    ref1 = ref[i], key = ref1.key, value = ref1.value;
    clone[key] = value;
  }
  return clone;
};
